version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blumenau-backend
    ports:
      - "8080:8080"
    networks:
      - blumenau-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: blumenau-frontend
    depends_on:
      - backend
    environment:
      # Dentro do Docker, o frontend acessa o backend pelo nome do servi√ßo: "backend"
      NEXT_PUBLIC_API_URL: http://backend:8080
    ports:
      - "3000:3000"
    networks:
      - blumenau-net

networks:
  blumenau-net:
    driver: bridge