version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: blumenau-backend
    ports:
      - "8080:8080"
    networks:
      - blumenau-net

  frontend:
    build:
      context: ./frontend
    container_name: blumenau-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:8080"
    depends_on:
      - backend
    networks:
      - blumenau-net

networks:
  blumenau-net:
    driver: bridge